apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - name: camera
        image: dpakapd/camera:v1
        securityContext:
          privileged: true
